In [2]:
import numpy as np

In [3]:
# 2차원 배열의 정보 확인
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [4]:
a2.ndim

2

In [5]:
a2.itemsize

4

In [6]:
a2.size

6

넘파이 모듈의 함수 특징

In [7]:
# 벡터화 연산
a = np.arange(6,10)
a

array([6, 7, 8, 9])

In [8]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [9]:
c = a * b
c

array([ 60,  77,  96, 117])

In [10]:
# 축 연산
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [11]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [12]:
np.sum(a2)

10

In [13]:
np.sum(a2,axis=0)

array([4, 6])

In [14]:
np.sum(a2,axis=1)

array([3, 7])

배열 할당과 검색

In [15]:
# 리스트 검색
x = list(range(1,10))
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
index = 1
x.__getitem__(index)

2

In [17]:
index = slice(1,3)
x.__getitem__(index)

[2, 3]

스칼라와 벡터 알아보기

In [18]:
a3 = np.arange(5,10)
a3

array([5, 6, 7, 8, 9])

In [19]:
a4 = np.linspace(1,10,13,endpoint=True,retstep=True)
a4

(array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ,  4.75,  5.5 ,  6.25,  7.  ,
         7.75,  8.5 ,  9.25, 10.  ]),
 0.75)

In [20]:
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [21]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [22]:
v=np.arange(3,5)
v

array([3, 4])

In [23]:
v_p=np.power(v,2)
v_p

array([ 9, 16], dtype=int32)

In [24]:
v_r = np.sqrt(v_p)
v_r

array([3., 4.])

In [25]:
e1 = np.array([1,0,0])
np.linalg.norm(e1)

1.0

행렬 만들기

In [26]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1)

2

In [27]:
# 팬시 검색
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
pos2 = np.array([1,2,2,2])
x[pos2]

array([2, 3, 3, 3])

In [29]:
c = x[pos2]


메소드로 검색2
 - 인덱스 번호 사용
 - take를 쓰면 나뉘어진 리스트를 한줄로 쭈욱 인덱스 부여함

In [30]:
b=np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [31]:
# take() : 가져오는 거
pos2=[[5,6],[8,9]]
b.take(pos2)

array([[ 6.,  7.],
       [ 9., 10.]])

In [32]:
pos1=[3,4]

In [33]:
c= b.copy()

In [34]:
# put() : 놓다, 변경
c.put(pos1,30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [38]:
# 행렬 만들기
A = np.array([[43],[44]])
type(A)
A.ndim
A.shape

(2, 1)

In [39]:
# 확장 및 축소
x = np.array([1,2])
x

array([1, 2])

In [41]:
y = np.expand_dims(x,axis=1)
y

array([[1],
       [2]])

In [42]:
x4 = np.array([[1,2,3],[4,5,6]])
x4

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
x4.flatten()

array([1, 2, 3, 4, 5, 6])

In [47]:
a = np.arange(1,10)
a.ndim


1

In [50]:
# np.eye()
# 대각선 행렬을 제외하고 0으로 채운 행렬 생성
# 기본값 : float
b = np.eye(5, dtype='int')
b

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [52]:
# np.dot()
# 계산 대상이 모두 벡터인 경우 두 벡터의 곱을 더해줌
a = np.array([1,2,3])
b = np.array([2,2,2])
np.dot(a,b)

12

In [67]:
# np.dot()
# 계산 대상이 모두 행렬인 경우 행렬의 곱 실행
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [68]:
b

array([[5, 6],
       [7, 8]])

In [69]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [70]:
# 전치행렬
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# 행렬의 슬라이스 검색
# 쉼표가 없으면 선형으로 생각해서 쭈욱 출력
# 쉼표 있으면 행렬로 생각해서 
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [74]:
a[1,:]

array([4, 5, 6])

In [96]:
a[:2, ...]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
# 논리 검색
L = np.random.randn(7,4)
L

array([[-2.55519255,  0.6307687 ,  0.73438523, -0.47416516],
       [-0.89516633,  0.3045772 ,  0.9898453 ,  0.5792701 ],
       [-0.92599329, -0.7767634 , -0.1500914 , -0.37781774],
       [ 1.32691367, -0.79431631, -0.27238665, -1.51341098],
       [-2.21885087, -0.28678677,  0.05664957,  0.09297666],
       [ 0.14323516,  0.22903005,  0.1106821 ,  0.43246648],
       [ 1.06076603,  0.37188769, -0.57255719,  0.91917712]])

In [101]:
L[L<0]

array([-2.55519255, -0.47416516, -0.89516633, -0.92599329, -0.7767634 ,
       -0.1500914 , -0.37781774, -0.79431631, -0.27238665, -1.51341098,
       -2.21885087, -0.28678677, -0.57255719])

In [102]:
L[L<0] = 999
L

array([[9.99000000e+02, 6.30768698e-01, 7.34385234e-01, 9.99000000e+02],
       [9.99000000e+02, 3.04577203e-01, 9.89845299e-01, 5.79270104e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [1.32691367e+00, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 5.66495663e-02, 9.29766560e-02],
       [1.43235156e-01, 2.29030049e-01, 1.10682099e-01, 4.32466479e-01],
       [1.06076603e+00, 3.71887690e-01, 9.99000000e+02, 9.19177123e-01]])