#### 성능지표 - 분류
 - 정확도 (Accuracy) : 전체 정답에서 맞춘 정답의 수
 - 정밀도 (Precision) : 모델(예측) 기준으로 모델이 True라고 한 것이 정답(실제) True 인 것
 - 재현율 (Reacll) : 실제 정답 기준으로 정답(실제)이 True라고 한 것이 모델(예측) True 인 것
 - F1-Score : 정밀도와 재현율 2가지를 조합한 점수
 - 오차행렬 (confusion Matrix) : 정답과 예측값의 관계도

[1] 모듈 로딩 및 데이터 준비

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score          # sklearn에서 제공하는 모델 성능평과 관련 모듈

In [3]:
# 데이터 로딩
digitBunch = load_digits(as_frame=True)

[2] 피쳐와 레이블 추출

In [8]:
# 0 ~ 9까지 숫자 이미지 데이터 값 들어있음
imgDF = digitBunch['data']

# 0 ~ 9 라벨
labelSR = digitBunch['target']
labelSR.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
## => 2진 분류를 위해서 7과 나머지 라벨 변경
mask = (labelSR==7)

## mask의 반대 ~mask

labelSR[~mask] = 0
labelSR[mask] = 1

In [17]:
labelSR.value_counts()

target
0    1618
1     179
Name: count, dtype: int64

[3] 학습용 데이터셋 준비

In [19]:
X_train, X_test, y_train, y_test = train_test_split(imgDF,labelSR,
                                                    stratify=labelSR,
                                                    random_state=1)

In [23]:
print(y_train.value_counts()/y_train.shape[0])
print(y_test.value_counts()/y_test.shape[0])

target
0    0.90052
1    0.09948
Name: count, dtype: float64
target
0    0.9
1    0.1
Name: count, dtype: float64


[4] 클래스 정의

In [24]:
# 사용자 정의 클래스 DubbyClass : 아무것도 하지 않는 클래스, 단순 테스트용
from sklearn.base import BaseEstimator

class MyClassfier(BaseEstimator):

    def fit(self,X,y):pass

    def predict(self,X) : return np.zeros((len(X),1),dtype=bool)

[5] 학습

In [25]:
# 인스턴스 생성
model = MyClassfier()

# 학습
model.fit(X_train, y_train)

[6] 예측 및 성능 평가

In [26]:
pre_ = model.predict(X_train)
pre_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

[6-1] 정확도는 불균형 데이터일 경우 신뢰할 수 없음

In [28]:
accuracy_score(y_train,pre_)

0.9005196733481812

[6-2] 오차행렬

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

In [33]:
# 정답과 예측값 전달
tn, fp, fn, tp = confusion_matrix(y_train,pre_, labels=[0,1]).reshape(-1)

In [36]:
confusion_matrix(y_train,pre_)

array([[1213,    0],
       [ 134,    0]], dtype=int64)

- 정밀도(Precision) 모델(예측)중심

In [38]:
from sklearn.metrics import precision_score

precision_score(y_train,pre_,zero_division=0)

0.0

- 재현율(Recall) : 정답(실제)중심

In [39]:
from sklearn.metrics import recall_score

recall_score(y_train,pre_)

0.0

In [41]:
y_test = [0,0,0,1,1, 1,0,0,0,1, 1,1,1,0,0, 0,0,0,0,0]
y_pre = [1,1,1,1,1, 1,0,1,0,1, 1,1,1,0,0, 0,0,0,0,0]

In [43]:
# 정답과 예측값 전달
(tn, fp, fn, tp) = confusion_matrix(y_test, y_pre).reshape(-1)
print(tn, fp, fn, tp)

9 4 0 7
