In [1]:
import numpy as np

자연 상수의 지수
 - 자연상수 e(2.17...)를 기준으로 처리

In [2]:
np.exp(0)

1.0

In [3]:
np.exp(-2)

0.1353352832366127

지수함수
 - 자연상수 e,2를 기준으로 지수 함수를 만들어서 배열의 값을 지수로 넣고 계산


In [5]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [6]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [7]:
np.power(np.e,x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])