#### Tensor 이해 - 생성
- Trensor란? pytorch에서 데이터를 저장하는 객체
  * pytorch에서 데이터를 저장하는 객체
  * 모델에 입력/출력 데이터 형태

In [1]:
import torch

print(f'torch.v : {torch.__version__}')

torch.v : 2.4.1


In [2]:
'''
함수기능 : 텐서 속성 정보 출력 함수
'''

def printinfo(obj,obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape : {obj.shape}')
    print(f'dim {obj.ndim}차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data : \n{obj.data}')

 - 텐서생성[1]torch.tensor()

In [5]:
## 데이터 1개(스칼라 생성)
dataTF = torch.tensor(10)
printinfo(dataTF,'dataTF')

dataTF = torch.tensor(10, dtype=torch.uint8)
printinfo(dataTF,'dataTF')


[dataTF]
shape : torch.Size([])
dim 0차원
dtype : torch.int64
device : cpu
data : 
10

[dataTF]
shape : torch.Size([])
dim 0차원
dtype : torch.uint8
device : cpu
data : 
10


In [18]:
## 데이터 1개(벡터 생성(1D))
dataTF = torch.tensor([[[[10]]]])
## []괄호의 숫자가 차원 수

printinfo(dataTF,'dataTF')

dataTF = torch.tensor([[[[10],[20]]]])
printinfo(dataTF,'dataTF')


[dataTF]
shape : torch.Size([1, 1, 1, 1])
dim 4차원
dtype : torch.int64
device : cpu
data : 
tensor([[[[10]]]])

[dataTF]
shape : torch.Size([1, 1, 2, 1])
dim 4차원
dtype : torch.int64
device : cpu
data : 
tensor([[[[10],
          [20]]]])


[dataTF]    
                   0축1축2축3축  
                    ↓  ↓  ↓  ↓  
shape : torch.Size([1, 1, 2, 1])  
                    ↑  ↑  ↑  ↑  
                    4D 3D 2행 1열    
dim 4차원  
dtype : torch.int64  
device : cpu  
data :   
tensor([[[[10],  
          [20]]]])  