#### Tensor 이해

In [ ]:
### 모듈 로딩
import torch

- Tensor생성 [2] torch.rand()  

In [ ]:
# 0<= ~<1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 ==> 몇 차원일지 알 수 없음!
torch.manual_seed(1)

dataTS1=torch.rand(3)           # 1D Vector
dataTS2=torch.rand(2,3)         # 2D Maxtrix
dataTS3=torch.rand(2,1,3)       # 3D 3D Tensor

In [ ]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- Tensor생성 [3] torch.randn()

In [ ]:
dataTS1=torch.randn(3)           # 1D Vector
dataTS2=torch.randn(2,3)         # 2D Maxtrix
dataTS3=torch.randn(2,1,3)       # 3D 3D Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([ 2.0731, -1.9578,  2.8238])
tensor([[ 0.2384, -0.6317,  1.3790],
        [ 0.6429, -0.4019,  2.5451]])
tensor([[[ 0.0080,  1.2720,  0.9502]],

        [[ 0.1889, -0.7525, -0.1523]]])


- Tensor생성[3]torch.randint()

In [ ]:
# 1D Vector
dataTS1=torch.randint(1,46,(6,))
dataTS1

tensor([38, 22, 25, 27,  4, 40])

In [ ]:
# 2D Vector
dataTS1=torch.randint(1,46,(4, 6))
dataTS1

tensor([[ 4, 19, 36, 40, 44, 15],
        [40, 40, 29,  1, 19, 35],
        [42,  1, 36, 24, 25, 42],
        [ 6, 25, 22, 30,  9, 37]])